# Generated by Django 2.2 on 2020-08-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_auto_20200808_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
