# Generated by Django 2.2 on 2020-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonExapp', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='pythonExapp.User'),
        ),
    ]
